import eslintComments from "@eslint-community/eslint-plugin-eslint-comments"
import html from "@html-eslint/eslint-plugin"
import htmlParser from "@html-eslint/parser"
import stylistic from "@stylistic/eslint-plugin"
import typescript from "@typescript-eslint/eslint-plugin"
import typescriptParser from "@typescript-eslint/parser"
import type {TSESLint} from "@typescript-eslint/utils"
import gitignore from "eslint-config-flat-gitignore"
import ascii from "eslint-plugin-ascii"
import clsx from "eslint-plugin-clsx"
import deMorgan from "eslint-plugin-de-morgan"
import depend from "eslint-plugin-depend"
import esX from "eslint-plugin-es-x"
import github from "eslint-plugin-github"
import htmlScript from "eslint-plugin-html"
import importNewlines from "eslint-plugin-import-newlines"
import importX from "eslint-plugin-import-x"
import jsdoc from "eslint-plugin-jsdoc"
import jsonc from "eslint-plugin-jsonc"
import jsxA11y from "eslint-plugin-jsx-a11y"
import markdown from "eslint-plugin-markdown"
import math from "eslint-plugin-math"
import n from "eslint-plugin-n"
import noUnsanitized from "eslint-plugin-no-unsanitized"
import nodeDependencies from "eslint-plugin-node-dependencies"
import packageJson from "eslint-plugin-package-json"
import preferLet from "eslint-plugin-prefer-let"
import promise from "eslint-plugin-promise"
import regexp from "eslint-plugin-regexp"
import security from "eslint-plugin-security"
import toml from "eslint-plugin-toml"
import unicorn from "eslint-plugin-unicorn"
import wc from "eslint-plugin-wc"
import yml from "eslint-plugin-yml"
import jsoncParser from "jsonc-eslint-parser"
import tomlParser from "toml-eslint-parser"
import yamlParser from "yaml-eslint-parser"
import {ignorePattern} from "./fragments/max-len.ts"

const e = "error"

const config: TSESLint.FlatConfig.ConfigArray = [
	//
	// Ignores
	//

	{
		name: "@vanyauhalin/git-ignores",
		ignores: gitignore().ignores,
	},
	{
		name: "@vanyauhalin/vanyauhalin-ignores",
		ignores: [
			"**/mise.lock",
			"**/pnpm-lock.yaml",
		],
	},

	//
	// Parsers and Processors
	//

	{
		name: "@vanyauhalin/html-parser",
		files: ["**/*.html"],
		languageOptions: {parser: htmlParser},
	},
	{
		name: "@vanyauhalin/jsonc-parser",
		files: ["**/*.json", "**/*.json5", "**/*.jsonc"],
		languageOptions: {parser: jsoncParser},
	},
	{
		name: "@vanyauhalin/markdown-processor",
		files: ["**/*.md"],
		processor: markdown.processors.markdown,
	},
	{
		name: "@vanyauhalin/toml-parser",
		files: ["**/*.toml"],
		languageOptions: {parser: tomlParser},
	},
	{
		name: "@vanyauhalin/typescript-parser",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx"],
		languageOptions: {
			parser: typescriptParser,
			parserOptions: {
				projectService: true,
			},
		},
	},
	{
		name: "@vanyauhalin/yaml-parser",
		files: ["**/*.yaml", "**/*.yml"],
		languageOptions: {parser: yamlParser},
	},

	// This integration should be after the main TypeScript definition.
	{
		name: "@vanyauhalin/markdown-processor/typescript-integration",
		files: ["**/*.md/*.cjs", "**/*.md/*.js", "**/*.md/*.jsx", "**/*.md/*.mjs", "**/*.md/*.cts", "**/*.md/*.mts", "**/*.md/*.ts", "**/*.md/*.tsx", "**/*.md/*.html"],
		languageOptions: {
			parser: typescriptParser,
			parserOptions: {
				ecmaFeatures: {
					impliedStrict: true,
				},
				program: null,
				project: false,
				projectService: false,
			},
		},
	},

	//
	// Plugins
	//

	{
		name: "@vanyauhalin/ascii-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {ascii},
	},
	{
		name: "@vanyauhalin/clsx-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {clsx},
	},
	{
		name: "@vanyauhalin/de-morgan",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {"de-morgan": deMorgan},
	},
	{
		name: "@vanyauhalin/depend-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {depend},
	},
	{
		name: "@vanyauhalin/es-x-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {"es-x": esX},
	},
	{
		name: "@vanyauhalin/eslint-comments-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {"eslint-comments": eslintComments},
	},
	{
		name: "@vanyauhalin/github-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {github},
	},
	{
		name: "@vanyauhalin/html-plugin",
		files: ["**/*.html"],
		plugins: {html},
	},
	{
		name: "@vanyauhalin/html-script-plugin",
		files: ["**/*.html"],
		plugins: {"html-script": htmlScript},
	},
	{
		name: "@vanyauhalin/import-newlines-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {"import-newlines": importNewlines},
	},
	{
		name: "@vanyauhalin/import-x-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {"import-x": importX},
	},
	{
		name: "@vanyauhalin/jsdoc-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {jsdoc},
	},
	{
		name: "@vanyauhalin/jsonc-plugin",
		files: ["**/*.json", "**/*.json5", "**/*.jsonc"],
		plugins: {jsonc},
	},
	{
		name: "@vanyauhalin/jsx-a11y-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {"jsx-a11y": jsxA11y},
	},
	{
		name: "@vanyauhalin/markdown-plugin",
		files: ["**/*.md"],
		plugins: {markdown},
	},
	{
		name: "@vanyauhalin/math-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {math},
	},
	{
		name: "@vanyauhalin/n-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {n},
	},
	{
		name: "@vanyauhalin/no-unsanitized-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {"no-unsanitized": noUnsanitized},
	},
	{
		name: "@vanyauhalin/node-dependencies-plugin",
		files: ["**/package.json"],
		plugins: {"node-dependencies": nodeDependencies},
	},
	{
		name: "@vanyauhalin/package-json-plugin",
		files: ["**/package.json"],
		plugins: {"package-json": packageJson},
	},
	{
		name: "@vanyauhalin/prefer-let-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {"prefer-let": preferLet},
	},
	{
		name: "@vanyauhalin/promise-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {promise},
	},
	{
		name: "@vanyauhalin/regexp-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {regexp},
	},
	{
		name: "@vanyauhalin/security-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {security},
	},
	{
		name: "@vanyauhalin/stylistic-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {stylistic},
	},
	{
		name: "@vanyauhalin/toml-plugin",
		files: ["**/*.toml"],
		plugins: {toml},
	},
	{
		name: "@vanyauhalin/typescript-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {typescript},
	},
	{
		name: "@vanyauhalin/unicorn-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {unicorn},
	},
	{
		name: "@vanyauhalin/wc-plugin",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		plugins: {wc},
	},
	{
		name: "@vanyauhalin/yml-plugin",
		files: ["**/*.yaml", "**/*.yml"],
		plugins: {yml},
	},

	//
	// Rules and Settings
	//

	{
		name: "@vanyauhalin/builtin-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"camelcase": e,
			"constructor-super": e,
			"curly": e,
			"default-case-last": e,
			"default-param-last": e,
			"dot-notation": e,
			"eqeqeq": e,
			"for-direction": e,
			"func-name-matching": e,
			"func-names": e,
			"func-style": [e, "declaration", {allowArrowFunctions: true}],
			"getter-return": e,
			"grouped-accessor-pairs": e,
			"logical-assignment-operators": e,
			"new-cap": e,
			"no-alert": e,
			"no-array-constructor": e,
			"no-async-promise-executor": e,
			"no-caller": e,
			"no-class-assign": e,
			"no-compare-neg-zero": e,
			"no-cond-assign": e,
			"no-const-assign": e,
			"no-constant-binary-expression": e,
			"no-constant-condition": e,
			"no-constructor-return": e,
			"no-debugger": e,
			"no-delete-var": e,
			"no-dupe-args": e,
			"no-dupe-class-members": e,
			"no-dupe-else-if": e,
			"no-dupe-keys": e,
			"no-duplicate-case": e,
			"no-else-return": e,
			"no-empty-character-class": e,
			"no-empty-pattern": e,
			"no-empty-static-block": e,
			"no-empty": e,
			"no-eq-null": e,
			"no-eval": e,
			"no-ex-assign": e,
			"no-extend-native": e,
			"no-extra-bind": e,
			"no-extra-boolean-cast": e,
			"no-extra-label": e,
			"no-fallthrough": e,
			"no-func-assign": e,
			"no-global-assign": e,
			"no-implicit-coercion": e,
			"no-implicit-globals": e,
			"no-implied-eval": e,
			"no-import-assign": e,
			"no-invalid-regexp": e,
			"no-invalid-this": e,
			"no-irregular-whitespace": e,
			"no-iterator": e,
			"no-label-var": e,
			"no-labels": e,
			"no-lone-blocks": e,
			"no-lonely-if": e,
			"no-loop-func": e,
			"no-loss-of-precision": e,
			"no-misleading-character-class": e,
			"no-multi-assign": e,
			"no-multi-str": e,
			"no-nested-ternary": e,
			"no-new-func": e,
			"no-new-native-nonconstructor": e,
			"no-new-wrappers": e,
			"no-new": e,
			"no-nonoctal-decimal-escape": e,
			"no-obj-calls": e,
			"no-object-constructor": e,
			"no-octal-escape": e,
			"no-octal": e,
			"no-plusplus": e,
			"no-promise-executor-return": e,
			"no-proto": e,
			"no-prototype-builtins": e,
			"no-redeclare": e,
			"no-regex-spaces": e,
			"no-return-assign": e,
			"no-script-url": e,
			"no-self-assign": e,
			"no-self-compare": e,
			"no-sequences": e,
			"no-setter-return": e,
			"no-shadow-restricted-names": e,
			"no-sparse-arrays": e,
			"no-ternary": e,
			"no-this-before-super": e,
			"no-throw-literal": e,
			"no-undef-init": e,
			"no-underscore-dangle": e,
			"no-unexpected-multiline": e,
			"no-unmodified-loop-condition": e,
			"no-unneeded-ternary": e,
			"no-unreachable-loop": e,
			"no-unreachable": e,
			"no-unsafe-finally": e,
			"no-unsafe-negation": e,
			"no-unsafe-optional-chaining": e,
			"no-unused-expressions": e,
			"no-unused-labels": e,
			"no-unused-private-class-members": e,
			"no-unused-vars": e,
			"no-useless-backreference": e,
			"no-useless-call": e,
			"no-useless-catch": e,
			"no-useless-computed-key": e,
			"no-useless-concat": e,
			"no-useless-constructor": e,
			"no-useless-escape": e,
			"no-useless-rename": e,
			"no-var": e,
			"no-void": e,
			"no-with": e,
			"object-shorthand": e,
			"one-var": [e, "never"],
			"operator-assignment": e,
			"prefer-arrow-callback": e,
			"prefer-const": e,
			"prefer-numeric-literals": e,
			"prefer-object-has-own": e,
			"prefer-object-spread": e,
			"prefer-promise-reject-errors": e,
			"prefer-regex-literals": e,
			"prefer-rest-params": e,
			"prefer-spread": e,
			"prefer-template": e,
			"radix": e,
			"require-await": e,
			"require-yield": e,
			"sort-imports": [e, {ignoreDeclarationSort: true}],
			"strict": [e, "never"],
			"symbol-description": e,
			"unicode-bom": e,
			"use-isnan": e,
			"valid-typeof": e,
			"vars-on-top": e,
			"yoda": e,
		},
	},
	{
		name: "@vanyauhalin/ascii-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"ascii/valid-name": e,
		},
	},
	{
		name: "@vanyauhalin/clsx-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"clsx/forbid-array-expressions": e,
			"clsx/forbid-false-inside-object-expressions": e,
			"clsx/forbid-true-inside-object-expressions": e,
			"clsx/no-redundant-clsx": e,
			"clsx/no-spreading": e,
			"clsx/prefer-logical-over-objects": e,
			"clsx/prefer-merged-neighboring-elements": e,
		},
	},
	{
		name: "@vanyauhalin/de-morgan-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"de-morgan/no-negated-conjunction": e,
			"de-morgan/no-negated-disjunction": e,
		},
	},
	{
		name: "@vanyauhalin/depend-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"depend/ban-dependencies": e,
		},
	},
	{
		name: "@vanyauhalin/es-x-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"es-x/no-array-from": e,
			"es-x/no-array-of": e,
			"es-x/no-array-prototype-at": e,
			"es-x/no-array-prototype-copywithin": e,
			"es-x/no-array-prototype-every": e,
			"es-x/no-array-prototype-fill": e,
			"es-x/no-array-prototype-filter": e,
			"es-x/no-array-prototype-find": e,
			"es-x/no-array-prototype-findindex": e,
			"es-x/no-array-prototype-findlast-findlastindex": e,
			"es-x/no-array-prototype-flat": e,
			"es-x/no-array-prototype-foreach": e,
			"es-x/no-array-prototype-keys": e,
			"es-x/no-array-prototype-lastindexof": e,
			"es-x/no-array-prototype-map": e,
			"es-x/no-array-prototype-reduce": e,
			"es-x/no-array-prototype-reduceright": e,
			"es-x/no-array-prototype-some": e,
			"es-x/no-array-prototype-toreversed": e,
			"es-x/no-array-prototype-tosorted": e,
			"es-x/no-array-prototype-tospliced": e,
			"es-x/no-array-prototype-values": e,
			"es-x/no-array-prototype-with": e,
			"es-x/no-class-static-block": e,
			"es-x/no-date-prototype-getyear-setyear": e,
			"es-x/no-date-prototype-togmtstring": e,
			"es-x/no-default-parameters": e,
			"es-x/no-escape-unescape": e,
			"es-x/no-exponential-operators": e,
			"es-x/no-export-ns-from": e,
			"es-x/no-function-declarations-in-if-statement-clauses-without-block": e,
			"es-x/no-initializers-in-for-in": e,
			"es-x/no-iterator-prototype-every": e,
			"es-x/no-iterator-prototype-filter": e,
			"es-x/no-iterator-prototype-find": e,
			"es-x/no-iterator-prototype-flatmap": e,
			"es-x/no-iterator-prototype-foreach": e,
			"es-x/no-iterator-prototype-map": e,
			"es-x/no-iterator-prototype-reduce": e,
			"es-x/no-iterator-prototype-some": e,
			"es-x/no-labelled-function-declarations": e,
			"es-x/no-legacy-object-prototype-accessor-methods": e,
			"es-x/no-logical-assignment-operators": e,
			"es-x/no-map-groupby": e,
			"es-x/no-new-target": e,
			"es-x/no-nonstandard-array-properties": e,
			"es-x/no-nonstandard-arraybuffer-properties": e,
			"es-x/no-nonstandard-atomics-properties": e,
			"es-x/no-nonstandard-bigint-properties": e,
			"es-x/no-nonstandard-boolean-properties": e,
			"es-x/no-nonstandard-dataview-properties": e,
			"es-x/no-nonstandard-date-properties": e,
			"es-x/no-nonstandard-finalizationregistry-properties": e,
			"es-x/no-nonstandard-function-properties": e,
			"es-x/no-nonstandard-intl-collator-properties": e,
			"es-x/no-nonstandard-intl-datetimeformat-properties": e,
			"es-x/no-nonstandard-intl-displaynames-properties": e,
			"es-x/no-nonstandard-intl-listformat-properties": e,
			"es-x/no-nonstandard-intl-locale-properties": e,
			"es-x/no-nonstandard-intl-numberformat-properties": e,
			"es-x/no-nonstandard-intl-pluralrules-properties": e,
			"es-x/no-nonstandard-intl-properties": e,
			"es-x/no-nonstandard-intl-relativetimeformat-properties": e,
			"es-x/no-nonstandard-intl-segmenter-properties": e,
			"es-x/no-nonstandard-iterator-properties": e,
			"es-x/no-nonstandard-json-properties": e,
			"es-x/no-nonstandard-map-properties": e,
			"es-x/no-nonstandard-math-properties": e,
			"es-x/no-nonstandard-number-properties": e,
			"es-x/no-nonstandard-object-properties": e,
			"es-x/no-nonstandard-promise-properties": e,
			"es-x/no-nonstandard-proxy-properties": e,
			"es-x/no-nonstandard-reflect-properties": e,
			"es-x/no-nonstandard-regexp-properties": e,
			"es-x/no-nonstandard-set-properties": e,
			"es-x/no-nonstandard-sharedarraybuffer-properties": e,
			"es-x/no-nonstandard-string-properties": e,
			"es-x/no-nonstandard-symbol-properties": e,
			"es-x/no-nonstandard-typed-array-properties": e,
			"es-x/no-nonstandard-weakmap-properties": e,
			"es-x/no-nonstandard-weakref-properties": e,
			"es-x/no-nonstandard-weakset-properties": e,
			"es-x/no-nullish-coalescing-operators": e,
			"es-x/no-numeric-separators": e,
			"es-x/no-object-assign": e,
			"es-x/no-object-create": e,
			"es-x/no-object-defineproperties": e,
			"es-x/no-object-defineproperty": e,
			"es-x/no-object-freeze": e,
			"es-x/no-object-fromentries": e,
			"es-x/no-object-getownpropertydescriptor": e,
			"es-x/no-object-getownpropertydescriptors": e,
			"es-x/no-object-getownpropertynames": e,
			"es-x/no-object-getownpropertysymbols": e,
			"es-x/no-object-getprototypeof": e,
			"es-x/no-object-groupby": e,
			"es-x/no-object-hasown": e,
			"es-x/no-object-is": e,
			"es-x/no-object-isextensible": e,
			"es-x/no-object-isfrozen": e,
			"es-x/no-object-issealed": e,
			"es-x/no-object-preventextensions": e,
			"es-x/no-object-seal": e,
			"es-x/no-object-setprototypeof": e,
			"es-x/no-optional-chaining": e,
			"es-x/no-private-in": e,
			"es-x/no-regexp-prototype-compile": e,
			"es-x/no-shadow-catch-param": e,
			"es-x/no-string-create-html-methods": e,
			"es-x/no-string-prototype-at": e,
			"es-x/no-string-prototype-substr": e,
			"es-x/no-string-prototype-trimleft-trimright": e,
			"es-x/no-typed-arrays": e,
			"es-x/no-unicode-codepoint-escapes": e,
		},
	},
	{
		name: "@vanyauhalin/eslint-comments-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"eslint-comments/disable-enable-pair": [e, {allowWholeFile: true}],
			"eslint-comments/no-aggregating-enable": e,
			"eslint-comments/no-duplicate-disable": e,
			"eslint-comments/no-unlimited-disable": e,
			"eslint-comments/no-unused-disable": e,
			"eslint-comments/no-unused-enable": e,
		},
	},
	{
		name: "@vanyauhalin/github-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"github/a11y-aria-label-is-well-formatted": e,
			"github/a11y-no-title-attribute": e,
			"github/a11y-role-supports-aria-props": e,
			"github/a11y-svg-has-accessible-name": e,
			"github/array-foreach": e,
			"github/get-attribute": e,
			"github/no-blur": e,
			"github/no-dataset": e,
			"github/no-dynamic-script-tag": e,
			"github/no-implicit-buggy-globals": e,
			"github/no-inner-html": e,
			"github/no-useless-passive": e,
			"github/prefer-observers": e,
			"github/require-passive-events": e,
			"github/unescaped-html-literal": e,
		},
	},
	{
		name: "@vanyauhalin/html-rules",
		files: ["**/*.html"],
		rules: {
			"html/element-newline": [e, {skip: ["pre", "code"], inline: ["$inline"]}],
			"html/id-naming-convention": [e, "kebab-case"],
			"html/indent": [e, "tab"],
			"html/lowercase": e,
			"html/no-abstract-roles": e,
			"html/no-accesskey-attrs": e,
			"html/no-aria-hidden-body": e,
			"html/no-duplicate-attrs": e,
			"html/no-duplicate-id": e,
			"html/no-extra-spacing-attrs": e,
			"html/no-extra-spacing-text": e,
			"html/no-inline-styles": e,
			"html/no-multiple-empty-lines": e,
			"html/no-multiple-h1": e,
			"html/no-non-scalable-viewport": e,
			"html/no-obsolete-tags": e,
			"html/no-positive-tabindex": e,
			"html/no-script-style-type": e,
			"html/no-skip-heading-levels": e,
			"html/no-target-blank": e,
			"html/no-trailing-spaces": e,
			"html/quotes": e,
			"html/require-button-type": e,
			"html/require-closing-tags": e,
			"html/require-frame-title": e,
			"html/require-img-alt": e,
			"html/require-lang": e,
			"html/require-li-container": e,
			"html/require-meta-charset": e,
			"html/require-meta-description": e,
			"html/require-meta-viewport": e,
			"html/require-open-graph-protocol": e,
			"html/require-title": e,
			"html/sort-attrs": [e, {priority: ["id", "type", "class", "style"]}],
		},
	},
	{
		name: "@vanyauhalin/html-script-settings",
		files: ["**/*.html"],
		settings: {
			"html-script/indent": "0",
			"html-script/report-bad-indent": e,
		},
	},
	{
		name: "@vanyauhalin/import-newlines-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"import-newlines/enforce": [e, {"items": Infinity, "max-len": 120, "semi": false}],
		},
	},
	{
		name: "@vanyauhalin/import-x-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"import-x/consistent-type-specifier-style": e,
			"import-x/default": e,
			"import-x/export": e,
			"import-x/extensions": [e, "always", {ignorePackages: true}],
			"import-x/first": e,
			"import-x/named": e,
			"import-x/namespace": e,
			"import-x/newline-after-import": e,
			"import-x/no-absolute-path": e,
			"import-x/no-amd": e,
			"import-x/no-commonjs": e,
			"import-x/no-cycle": e,
			"import-x/no-default-export": e,
			"import-x/no-deprecated": e,
			"import-x/no-duplicates": e,
			"import-x/no-empty-named-blocks": e,
			"import-x/no-extraneous-dependencies": e,
			"import-x/no-import-module-exports": e,
			"import-x/no-mutable-exports": e,
			"import-x/no-named-as-default-member": e,
			"import-x/no-named-as-default": e,
			"import-x/no-named-default": e,
			"import-x/no-self-import": e,
			"import-x/no-unassigned-import": e,
			"import-x/no-unused-modules": e,
			"import-x/no-useless-path-segments": e,
			"import-x/no-webpack-loader-syntax": e,
		},
	},
	{
		name: "@vanyauhalin/jsdoc-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"jsdoc/check-access": e,
			"jsdoc/check-alignment": e,
			"jsdoc/check-param-names": e,
			"jsdoc/check-property-names": e,
			"jsdoc/check-syntax": e,
			"jsdoc/check-tag-names": e,
			"jsdoc/check-template-names": e,
			"jsdoc/check-types": e,
			"jsdoc/empty-tags": e,
			"jsdoc/implements-on-classes": e,
			"jsdoc/imports-as-dependencies": e,
			"jsdoc/lines-before-block": e,
			"jsdoc/multiline-blocks": e,
			"jsdoc/no-bad-blocks": e,
			"jsdoc/no-blank-block-descriptions": e,
			"jsdoc/no-blank-blocks": e,
			"jsdoc/no-defaults": e,
			"jsdoc/no-multi-asterisks": e,
			"jsdoc/no-undefined-types": e,
			"jsdoc/require-asterisk-prefix": e,
			"jsdoc/require-hyphen-before-param-description": [e, "never"],
			"jsdoc/require-param-name": e,
			"jsdoc/require-param-type": e,
			"jsdoc/require-param": e,
			"jsdoc/require-property-name": e,
			"jsdoc/require-property-type": e,
			"jsdoc/require-returns-check": e,
			"jsdoc/require-returns-type": e,
			"jsdoc/require-returns": e,
			"jsdoc/require-template": e,
			"jsdoc/require-throws": e,
			"jsdoc/require-yields-check": e,
			"jsdoc/require-yields": e,
			"jsdoc/valid-types": e,
		},
	},
	{
		name: "@vanyauhalin/jsdoc-rules/typescript-exceptions",
		files: ["**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx"],
		rules: {
			"jsdoc/no-types": e,
			"jsdoc/no-undefined-types": "off",
			"jsdoc/require-param-type": "off",
			"jsdoc/require-param": "off",
			"jsdoc/require-property-type": "off",
			"jsdoc/require-returns-type": "off",
			"jsdoc/require-returns": "off",
			"jsdoc/require-template": "off",
			"jsdoc/require-yields": "off",
		},
	},
	{
		name: "@vanyauhalin/jsonc-rules",
		files: ["**/*.json", "**/*.json5", "**/*.jsonc"],
		rules: {
			"jsonc/array-bracket-newline": e,
			"jsonc/array-bracket-spacing": e,
			"jsonc/comma-dangle": e,
			"jsonc/comma-style": e,
			"jsonc/indent": [e, "tab"],
			"jsonc/key-spacing": e,
			"jsonc/no-bigint-literals": e,
			"jsonc/no-binary-expression": e,
			"jsonc/no-binary-numeric-literals": e,
			"jsonc/no-comments": e,
			"jsonc/no-dupe-keys": e,
			"jsonc/no-escape-sequence-in-identifier": e,
			"jsonc/no-floating-decimal": e,
			"jsonc/no-hexadecimal-numeric-literals": e,
			"jsonc/no-infinity": e,
			"jsonc/no-irregular-whitespace": e,
			"jsonc/no-multi-str": e,
			"jsonc/no-nan": e,
			"jsonc/no-number-props": e,
			"jsonc/no-numeric-separators": e,
			"jsonc/no-octal-escape": e,
			"jsonc/no-octal-numeric-literals": e,
			"jsonc/no-octal": e,
			"jsonc/no-parenthesized": e,
			"jsonc/no-plus-sign": e,
			"jsonc/no-regexp-literals": e,
			"jsonc/no-sparse-arrays": e,
			"jsonc/no-template-literals": e,
			"jsonc/no-undefined-value": e,
			"jsonc/no-unicode-codepoint-escapes": e,
			"jsonc/no-useless-escape": e,
			"jsonc/object-curly-newline": e,
			"jsonc/object-curly-spacing": e,
			"jsonc/object-property-newline": e,
			"jsonc/quote-props": e,
			"jsonc/quotes": e,
			"jsonc/space-unary-ops": e,
			"jsonc/valid-json-number": e,
		},
	},
	{
		name: "@vanyauhalin/jsonc-rules/json5-exceptions",
		files: ["**/*.json5"],
		rules: {
			"jsonc/comma-dangle": [e, "always-multiline"],
			"jsonc/no-comments": "off",
			"jsonc/quote-props": [e, "consistent"],
		},
	},
	{
		name: "@vanyauhalin/jsonc-rules/jsonc-exceptions",
		files: ["**/*.jsonc"],
		rules: {
			"jsonc/no-comments": "off",
		},
	},
	{
		name: "@vanyauhalin/jsx-a11y-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"jsx-a11y/alt-text": e,
			"jsx-a11y/anchor-has-content": e,
			"jsx-a11y/anchor-is-valid": e,
			"jsx-a11y/aria-activedescendant-has-tabindex": e,
			"jsx-a11y/aria-props": e,
			"jsx-a11y/aria-proptypes": e,
			"jsx-a11y/aria-role": e,
			"jsx-a11y/aria-unsupported-elements": e,
			"jsx-a11y/autocomplete-valid": e,
			"jsx-a11y/click-events-have-key-events": e,
			"jsx-a11y/heading-has-content": e,
			"jsx-a11y/html-has-lang": e,
			"jsx-a11y/iframe-has-title": e,
			"jsx-a11y/img-redundant-alt": e,
			"jsx-a11y/interactive-supports-focus": e,
			"jsx-a11y/label-has-associated-control": e,
			"jsx-a11y/lang": e,
			"jsx-a11y/media-has-caption": e,
			"jsx-a11y/mouse-events-have-key-events": e,
			"jsx-a11y/no-access-key": e,
			"jsx-a11y/no-aria-hidden-on-focusable": e,
			"jsx-a11y/no-autofocus": e,
			"jsx-a11y/no-distracting-elements": e,
			"jsx-a11y/no-interactive-element-to-noninteractive-role": e,
			"jsx-a11y/no-noninteractive-element-interactions": e,
			"jsx-a11y/no-noninteractive-element-to-interactive-role": e,
			"jsx-a11y/no-noninteractive-tabindex": e,
			"jsx-a11y/no-redundant-roles": e,
			"jsx-a11y/no-static-element-interactions": e,
			"jsx-a11y/prefer-tag-over-role": e,
			"jsx-a11y/role-has-required-aria-props": e,
			"jsx-a11y/role-supports-aria-props": e,
			"jsx-a11y/scope": e,
			"jsx-a11y/tabindex-no-positive": e,
		},
	},
	{
		name: "@vanyauhalin/math-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"math/abs": [e, {prefer: "Math.abs"}],
			"math/no-static-infinity-calculations": e,
			"math/no-static-nan-calculations": e,
			"math/prefer-math-cbrt": e,
			"math/prefer-math-e": e,
			"math/prefer-math-hypot": e,
			"math/prefer-math-ln10": e,
			"math/prefer-math-ln2": e,
			"math/prefer-math-log10": e,
			"math/prefer-math-log10e": e,
			"math/prefer-math-log2": e,
			"math/prefer-math-log2e": e,
			"math/prefer-math-pi": e,
			"math/prefer-math-sqrt": e,
			"math/prefer-math-sqrt1-2": e,
			"math/prefer-math-sqrt2": e,
			"math/prefer-math-trunc": e,
			"math/prefer-number-epsilon": e,
			"math/prefer-number-is-finite": e,
			"math/prefer-number-is-integer": e,
			"math/prefer-number-is-nan": e,
			"math/prefer-number-is-safe-integer": e,
			"math/prefer-number-max-safe-integer": e,
			"math/prefer-number-max-value": e,
			"math/prefer-number-min-safe-integer": e,
		},
	},
	{
		name: "@vanyauhalin/n-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"n/exports-style": e,
			"n/hashbang": e,
			"n/no-deprecated-api": e,
			"n/no-exports-assign": e,
			"n/no-new-require": e,
			"n/no-path-concat": e,
			"n/prefer-global/buffer": e,
			"n/prefer-global/console": e,
			"n/prefer-global/process": e,
			"n/prefer-global/text-decoder": e,
			"n/prefer-global/text-encoder": e,
			"n/prefer-global/url": e,
			"n/prefer-node-protocol": e,
			"n/process-exit-as-throw": e,
		},
	},
	{
		name: "@vanyauhalin/no-unsanitized-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"no-unsanitized/method": [e, {}, {import: {objectMatches: []}}],
			"no-unsanitized/property": e,
		},
	},
	{
		name: "@vanyauhalin/node-dependencies-rules",
		files: ["**/package.json"],
		rules: {
			"node-dependencies/absolute-version": [e, {dependencies: "always", peerDependencies: "never", optionalDependencies: "always", devDependencies: "always"}],
			"node-dependencies/compat-engines": e,
			"node-dependencies/no-deprecated": e,
			"node-dependencies/no-dupe-deps": e,
			"node-dependencies/prefer-caret-range-version": e,
			"node-dependencies/prefer-tilde-range-version": e,
			"node-dependencies/valid-semver": e,
		},
	},
	{
		name: "@vanyauhalin/package-json-rules",
		files: ["**/package.json"],
		rules: {
			"package-json/order-properties": e,
			"package-json/repository-shorthand": e,
			"package-json/sort-collections": e,
			"package-json/unique-dependencies": e,
			"package-json/valid-local-dependency": e,
			"package-json/valid-name": e,
			"package-json/valid-package-def": e,
			"package-json/valid-repository-directory": e,
			"package-json/valid-version": e,
		},
	},
	{
		name: "@vanyauhalin/prefer-let-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"prefer-const": "off",
			"prefer-let/prefer-let": e,
		},
	},
	{
		name: "@vanyauhalin/promise-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"promise/always-return": e,
			"promise/catch-or-return": e,
			"promise/no-callback-in-promise": e,
			"promise/no-multiple-resolved": e,
			"promise/no-nesting": e,
			"promise/no-new-statics": e,
			"promise/no-return-in-finally": e,
			"promise/no-return-wrap": e,
			"promise/param-names": [e, {rejectPattern: "^(_+|rej)$", resolvePattern: "^(_+|res)$"}],
			"promise/prefer-await-to-then": e,
			"promise/prefer-catch": e,
			"promise/spec-only": e,
			"promise/valid-params": e,
		},
	},
	{
		name: "@vanyauhalin/regexp-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"regexp/confusing-quantifier": e,
			"regexp/control-character-escape": e,
			"regexp/hexadecimal-escape": [e, "never"],
			"regexp/letter-case": e,
			"regexp/match-any": e,
			"regexp/negation": e,
			"regexp/no-contradiction-with-assertion": e,
			"regexp/no-dupe-characters-character-class": e,
			"regexp/no-dupe-disjunctions": e,
			"regexp/no-empty-alternative": e,
			"regexp/no-empty-capturing-group": e,
			"regexp/no-empty-character-class": e,
			"regexp/no-empty-group": e,
			"regexp/no-empty-lookarounds-assertion": e,
			"regexp/no-empty-string-literal": e,
			"regexp/no-escape-backspace": e,
			"regexp/no-extra-lookaround-assertions": e,
			"regexp/no-invalid-regexp": e,
			"regexp/no-invisible-character": e,
			"regexp/no-lazy-ends": e,
			"regexp/no-legacy-features": e,
			"regexp/no-misleading-capturing-group": e,
			"regexp/no-misleading-unicode-character": e,
			"regexp/no-missing-g-flag": e,
			"regexp/no-non-standard-flag": e,
			"regexp/no-obscure-range": e,
			"regexp/no-optional-assertion": e,
			"regexp/no-potentially-useless-backreference": e,
			"regexp/no-super-linear-backtracking": e,
			"regexp/no-trivially-nested-assertion": e,
			"regexp/no-trivially-nested-quantifier": e,
			"regexp/no-unused-capturing-group": e,
			"regexp/no-useless-assertions": e,
			"regexp/no-useless-backreference": e,
			"regexp/no-useless-character-class": e,
			"regexp/no-useless-dollar-replacements": e,
			"regexp/no-useless-escape": e,
			"regexp/no-useless-flag": e,
			"regexp/no-useless-lazy": e,
			"regexp/no-useless-non-capturing-group": e,
			"regexp/no-useless-quantifier": e,
			"regexp/no-useless-range": e,
			"regexp/no-useless-set-operand": e,
			"regexp/no-useless-string-literal": e,
			"regexp/no-useless-two-nums-quantifier": e,
			"regexp/no-zero-quantifier": e,
			"regexp/optimal-lookaround-quantifier": e,
			"regexp/optimal-quantifier-concatenation": e,
			"regexp/prefer-character-class": e,
			"regexp/prefer-d": e,
			"regexp/prefer-lookaround": e,
			"regexp/prefer-plus-quantifier": e,
			"regexp/prefer-predefined-assertion": e,
			"regexp/prefer-quantifier": e,
			"regexp/prefer-question-quantifier": e,
			"regexp/prefer-range": e,
			"regexp/prefer-regexp-exec": e,
			"regexp/prefer-regexp-test": e,
			"regexp/prefer-set-operation": e,
			"regexp/prefer-star-quantifier": e,
			"regexp/prefer-w": e,
			"regexp/simplify-set-operations": e,
			"regexp/sort-flags": e,
			"regexp/strict": e,
			"regexp/unicode-escape": [e, "unicodeEscape"],
			"regexp/use-ignore-case": e,
		},
	},
	{
		name: "@vanyauhalin/security-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"security/detect-bidi-characters": e,
			"security/detect-buffer-noassert": e,
			"security/detect-child-process": e,
			"security/detect-disable-mustache-escape": e,
			"security/detect-eval-with-expression": e,
			"security/detect-new-buffer": e,
			"security/detect-no-csrf-before-method-override": e,
			"security/detect-non-literal-require": e,
			"security/detect-possible-timing-attacks": e,
			"security/detect-pseudoRandomBytes": e,
		},
	},
	{
		name: "@vanyauhalin/stylistic-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"stylistic/array-bracket-newline": [e, "consistent"],
			"stylistic/array-bracket-spacing": e,
			"stylistic/array-element-newline": [e, "consistent"],
			"stylistic/arrow-parens": e,
			"stylistic/arrow-spacing": e,
			"stylistic/block-spacing": [e, "never"],
			"stylistic/brace-style": e,
			"stylistic/comma-dangle": [e, "always-multiline"],
			"stylistic/comma-spacing": e,
			"stylistic/comma-style": e,
			"stylistic/computed-property-spacing": e,
			"stylistic/dot-location": e,
			"stylistic/eol-last": e,
			"stylistic/function-call-argument-newline": [e, "consistent"],
			"stylistic/function-call-spacing": e,
			"stylistic/function-paren-newline": [e, "consistent"],
			"stylistic/generator-star-spacing": e,
			"stylistic/implicit-arrow-linebreak": e,
			"stylistic/indent-binary-ops": [e, "tab"],
			"stylistic/indent": [e, "tab", {SwitchCase: 0}],
			"stylistic/jsx-child-element-spacing": e,
			"stylistic/jsx-closing-bracket-location": [e, "line-aligned"],
			"stylistic/jsx-closing-tag-location": [e, "line-aligned"],
			"stylistic/jsx-curly-brace-presence": [e, {props: "never", children: "never", propElementValues: "always"}],
			"stylistic/jsx-curly-newline": e,
			"stylistic/jsx-curly-spacing": e,
			"stylistic/jsx-equals-spacing": e,
			"stylistic/jsx-first-prop-new-line": e,
			"stylistic/jsx-indent-props": [e, "tab"],
			"stylistic/jsx-newline": [e, {prevent: true}],
			"stylistic/jsx-pascal-case": e,
			"stylistic/jsx-props-no-multi-spaces": e,
			"stylistic/jsx-quotes": e,
			"stylistic/jsx-tag-spacing": e,
			"stylistic/key-spacing": e,
			"stylistic/keyword-spacing": e,
			"stylistic/linebreak-style": e,
			"stylistic/max-len": [e, {code: 100, tabWidth: 2, ignorePattern, ignoreComments: false, ignoreTrailingComments: true, ignoreUrls: true, ignoreStrings: true, ignoreTemplateLiterals: true, ignoreRegExpLiterals: true}],
			"stylistic/max-statements-per-line": e,
			"stylistic/member-delimiter-style": [e, {multiline: {delimiter: "none", requireLast: false}, singleline: {delimiter: "semi", requireLast: false}, multilineDetection: "brackets"}],
			"stylistic/multiline-ternary": e,
			"stylistic/new-parens": e,
			"stylistic/no-confusing-arrow": e,
			"stylistic/no-extra-parens": e,
			"stylistic/no-extra-semi": e,
			"stylistic/no-floating-decimal": e,
			"stylistic/no-mixed-spaces-and-tabs": e,
			"stylistic/no-multi-spaces": e,
			"stylistic/no-multiple-empty-lines": [e, {max: 1, maxBOF: 0, maxEOF: 0}],
			"stylistic/no-trailing-spaces": e,
			"stylistic/no-whitespace-before-property": e,
			"stylistic/nonblock-statement-body-position": e,
			"stylistic/object-curly-newline": e,
			"stylistic/object-curly-spacing": e,
			"stylistic/object-property-newline": [e, {allowAllPropertiesOnSameLine: true}],
			"stylistic/one-var-declaration-per-line": e,
			"stylistic/operator-linebreak": [e, "after"],
			"stylistic/padded-blocks": [e, "never"],
			"stylistic/quote-props": [e, "consistent-as-needed"],
			"stylistic/quotes": [e, "double", {avoidEscape: true, allowTemplateLiterals: true}],
			"stylistic/rest-spread-spacing": e,
			"stylistic/semi-spacing": e,
			"stylistic/semi-style": [e, "first"],
			"stylistic/semi": [e, "never"],
			"stylistic/space-before-blocks": e,
			"stylistic/space-before-function-paren": [e, "never"],
			"stylistic/space-in-parens": e,
			"stylistic/space-infix-ops": e,
			"stylistic/space-unary-ops": e,
			"stylistic/spaced-comment": e,
			"stylistic/switch-colon-spacing": e,
			"stylistic/template-curly-spacing": e,
			"stylistic/template-tag-spacing": e,
			"stylistic/type-annotation-spacing": e,
			"stylistic/type-generic-spacing": e,
			"stylistic/type-named-tuple-spacing": e,
			"stylistic/wrap-iife": [e, "inside"],
			"stylistic/yield-star-spacing": e,
		},
	},
	{
		name: "@vanyauhalin/toml-rules",
		files: ["**/*.toml"],
		rules: {
			"toml/array-bracket-newline": e,
			"toml/array-bracket-spacing": e,
			"toml/array-element-newline": e,
			"toml/comma-style": e,
			"toml/indent": e,
			"toml/inline-table-curly-spacing": [e, "never", {arraysInObjects: false, objectsInObjects: false}],
			"toml/key-spacing": e,
			"toml/keys-order": e,
			"toml/no-mixed-type-in-array": e,
			"toml/no-non-decimal-integer": e,
			"toml/no-space-dots": e,
			"toml/no-unreadable-number-separator": e,
			"toml/padding-line-between-pairs": e,
			"toml/padding-line-between-tables": e,
			"toml/precision-of-fractional-seconds": e,
			"toml/precision-of-integer": e,
			"toml/quoted-keys": e,
			"toml/spaced-comment": e,
			"toml/table-bracket-spacing": e,
			"toml/tables-order": e,
		},
	},
	{
		name: "@vanyauhalin/typescript-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"typescript/adjacent-overload-signatures": e,
			"typescript/array-type": e,
			"typescript/await-thenable": e,
			"typescript/ban-tslint-comment": e,
			"typescript/class-literal-property-style": [e, "getters"],
			"typescript/consistent-generic-constructors": e,
			"typescript/consistent-indexed-object-style": e,
			"typescript/consistent-type-assertions": e,
			"typescript/consistent-type-definitions": e,
			"typescript/consistent-type-imports": e,
			"typescript/default-param-last": e,
			"typescript/dot-notation": e,
			"typescript/explicit-function-return-type": [e, {allowConciseArrowFunctionExpressionsStartingWithVoid: false, allowDirectConstAssertionInArrowFunctions: true, allowExpressions: true, allowFunctionsWithoutTypeParameters: false, allowHigherOrderFunctions: true, allowIIFEs: false, allowTypedFunctionExpressions: true}],
			"typescript/explicit-module-boundary-types": e,
			"typescript/method-signature-style": [e, "method"],
			"typescript/no-array-constructor": e,
			"typescript/no-array-delete": e,
			"typescript/no-base-to-string": e,
			"typescript/no-confusing-non-null-assertion": e,
			"typescript/no-confusing-void-expression": e,
			"typescript/no-deprecated": e,
			"typescript/no-dupe-class-members": e,
			"typescript/no-duplicate-enum-values": e,
			"typescript/no-duplicate-type-constituents": e,
			"typescript/no-dynamic-delete": e,
			"typescript/no-empty-object-type": [e, {allowInterfaces: "always"}],
			"typescript/no-explicit-any": e,
			"typescript/no-extra-non-null-assertion": e,
			"typescript/no-floating-promises": e,
			"typescript/no-for-in-array": e,
			"typescript/no-implied-eval": e,
			"typescript/no-inferrable-types": e,
			"typescript/no-invalid-this": e,
			"typescript/no-invalid-void-type": [e, {allowAsThisParameter: true, allowInGenericTypeArguments: true}],
			"typescript/no-loop-func": e,
			"typescript/no-meaningless-void-operator": e,
			"typescript/no-misused-new": e,
			"typescript/no-misused-promises": e,
			"typescript/no-mixed-enums": e,
			"typescript/no-namespace": [e, {allowDeclarations: true}],
			"typescript/no-non-null-asserted-nullish-coalescing": e,
			"typescript/no-non-null-asserted-optional-chain": e,
			"typescript/no-non-null-assertion": e,
			"typescript/no-redeclare": e,
			"typescript/no-redundant-type-constituents": e,
			"typescript/no-require-imports": e,
			"typescript/no-this-alias": e,
			"typescript/no-unnecessary-boolean-literal-compare": e,
			"typescript/no-unnecessary-parameter-property-assignment": e,
			"typescript/no-unnecessary-qualifier": e,
			"typescript/no-unnecessary-template-expression": e,
			"typescript/no-unnecessary-type-arguments": e,
			"typescript/no-unnecessary-type-assertion": e,
			"typescript/no-unnecessary-type-constraint": e,
			"typescript/no-unsafe-declaration-merging": e,
			"typescript/no-unsafe-enum-comparison": e,
			"typescript/no-unsafe-function-type": e,
			"typescript/no-unsafe-unary-minus": e,
			"typescript/no-unused-expressions": e,
			"typescript/no-unused-vars": [e, {args: "all", argsIgnorePattern: "^_+", caughtErrors: "all", caughtErrorsIgnorePattern: "^_+", destructuredArrayIgnorePattern: "^_+", ignoreRestSiblings: true, varsIgnorePattern: "^_+"}],
			"typescript/no-useless-constructor": e,
			"typescript/no-useless-empty-export": e,
			"typescript/no-wrapper-object-types": e,
			"typescript/non-nullable-type-assertion-style": e,
			"typescript/only-throw-error": e,
			"typescript/parameter-properties": e,
			"typescript/prefer-as-const": e,
			"typescript/prefer-enum-initializers": e,
			"typescript/prefer-find": e,
			"typescript/prefer-for-of": e,
			"typescript/prefer-function-type": e,
			"typescript/prefer-includes": e,
			"typescript/prefer-literal-enum-member": e,
			"typescript/prefer-namespace-keyword": e,
			"typescript/prefer-promise-reject-errors": e,
			"typescript/prefer-reduce-type-parameter": e,
			"typescript/prefer-regexp-exec": e,
			"typescript/prefer-return-this-type": e,
			"typescript/prefer-string-starts-ends-with": e,
			"typescript/promise-function-async": e,
			"typescript/related-getter-setter-pairs": e,
			"typescript/require-array-sort-compare": e,
			"typescript/require-await": e,
			"typescript/restrict-plus-operands": e,
			"typescript/restrict-template-expressions": e,
			"typescript/return-await": [e, "always"],
			"typescript/switch-exhaustiveness-check": [e, {allowDefaultCaseForExhaustiveSwitch: true, considerDefaultExhaustiveForUnions: true, requireDefaultForNonUnion: false}],
			"typescript/triple-slash-reference": e,
			"typescript/unbound-method": e,
			"typescript/unified-signatures": e,
			"typescript/use-unknown-in-catch-callback-variable": e,
		},
	},
	{
		name: "@vanyauhalin/typescript-rules/builtin-conflicts",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"default-param-last": "off",
			"dot-notation": "off",
			"no-array-constructor": "off",
			"no-dupe-class-members": "off",
			"no-invalid-this": "off",
			"no-loop-func": "off",
			"no-redeclare": "off",
			"no-throw-literal": "off",
			"no-unused-expressions": "off",
			"no-unused-vars": "off",
			"require-await": "off",
		},
	},
	{
		name: "@vanyauhalin/typescript-rules/javascript-exceptions",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs"],
		rules: {
			"typescript/explicit-function-return-type": "off",
			"typescript/explicit-module-boundary-types": "off",
		},
	},
	{
		name: "@vanyauhalin/typescript-rules/html-script-exceptions",
		files: ["**/*.html"],
		rules: {
			"typescript/await-thenable": "off",
			"typescript/consistent-type-imports": "off",
			"typescript/dot-notation": "off",
			"typescript/naming-convention": "off",
			"typescript/no-array-delete": "off",
			"typescript/no-base-to-string": "off",
			"typescript/no-confusing-void-expression": "off",
			"typescript/no-deprecated": "off",
			"typescript/no-duplicate-type-constituents": "off",
			"typescript/no-floating-promises": "off",
			"typescript/no-for-in-array": "off",
			"typescript/no-implied-eval": "off",
			"typescript/no-meaningless-void-operator": "off",
			"typescript/no-misused-promises": "off",
			"typescript/no-mixed-enums": "off",
			"typescript/no-redundant-type-constituents": "off",
			"typescript/no-unnecessary-boolean-literal-compare": "off",
			"typescript/no-unnecessary-qualifier": "off",
			"typescript/no-unnecessary-template-expression": "off",
			"typescript/no-unnecessary-type-arguments": "off",
			"typescript/no-unnecessary-type-assertion": "off",
			"typescript/no-unsafe-enum-comparison": "off",
			"typescript/no-unsafe-unary-minus": "off",
			"typescript/non-nullable-type-assertion-style": "off",
			"typescript/only-throw-error": "off",
			"typescript/prefer-find": "off",
			"typescript/prefer-includes": "off",
			"typescript/prefer-nullish-coalescing": "off",
			"typescript/prefer-promise-reject-errors": "off",
			"typescript/prefer-reduce-type-parameter": "off",
			"typescript/prefer-regexp-exec": "off",
			"typescript/prefer-return-this-type": "off",
			"typescript/prefer-string-starts-ends-with": "off",
			"typescript/promise-function-async": "off",
			"typescript/related-getter-setter-pairs": "off",
			"typescript/require-array-sort-compare": "off",
			"typescript/require-await": "off",
			"typescript/restrict-plus-operands": "off",
			"typescript/restrict-template-expressions": "off",
			"typescript/return-await": "off",
			"typescript/switch-exhaustiveness-check": "off",
			"typescript/unbound-method": "off",
			"typescript/use-unknown-in-catch-callback-variable": "off",
		},
	},
	{
		name: "@vanyauhalin/unicorn-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"unicorn/better-regex": e,
			"unicorn/catch-error-name": [e, {name: "err"}],
			"unicorn/consistent-empty-array-spread": e,
			"unicorn/consistent-existence-index-check": e,
			"unicorn/custom-error-definition": e,
			"unicorn/empty-brace-spaces": e,
			"unicorn/error-message": e,
			"unicorn/expiring-todo-comments": e,
			"unicorn/explicit-length-check": [e, {"non-zero": "not-equal"}],
			"unicorn/filename-case": e,
			"unicorn/import-style": e,
			"unicorn/new-for-builtins": e,
			"unicorn/no-anonymous-default-export": e,
			"unicorn/no-array-for-each": e,
			"unicorn/no-array-method-this-argument": e,
			"unicorn/no-array-reduce": e,
			"unicorn/no-await-expression-member": e,
			"unicorn/no-await-in-promise-methods": e,
			"unicorn/no-console-spaces": e,
			"unicorn/no-document-cookie": e,
			"unicorn/no-empty-file": e,
			"unicorn/no-for-loop": e,
			"unicorn/no-hex-escape": e,
			"unicorn/no-instanceof-array": e,
			"unicorn/no-invalid-fetch-options": e,
			"unicorn/no-invalid-remove-event-listener": e,
			"unicorn/no-length-as-slice-end": e,
			"unicorn/no-lonely-if": e,
			"unicorn/no-negation-in-equality-check": e,
			"unicorn/no-nested-ternary": e,
			"unicorn/no-new-array": e,
			"unicorn/no-new-buffer": e,
			"unicorn/no-object-as-default-parameter": e,
			"unicorn/no-process-exit": e,
			"unicorn/no-single-promise-in-promise-methods": e,
			"unicorn/no-thenable": e,
			"unicorn/no-this-assignment": e,
			"unicorn/no-typeof-undefined": e,
			"unicorn/no-unnecessary-await": e,
			"unicorn/no-unnecessary-polyfills": e,
			"unicorn/no-unreadable-array-destructuring": e,
			"unicorn/no-unreadable-iife": e,
			"unicorn/no-useless-fallback-in-spread": e,
			"unicorn/no-useless-length-check": e,
			"unicorn/no-useless-promise-resolve-reject": e,
			"unicorn/no-useless-spread": e,
			"unicorn/no-useless-switch-case": e,
			"unicorn/no-useless-undefined": [e, {checkArguments: false, checkArrowFunctionBody: false}],
			"unicorn/no-zero-fractions": e,
			"unicorn/number-literal-case": e,
			"unicorn/prefer-add-event-listener": e,
			"unicorn/prefer-array-find": e,
			"unicorn/prefer-array-flat-map": e,
			"unicorn/prefer-array-flat": e,
			"unicorn/prefer-array-index-of": e,
			"unicorn/prefer-array-some": e,
			"unicorn/prefer-blob-reading-methods": e,
			"unicorn/prefer-code-point": e,
			"unicorn/prefer-date-now": e,
			"unicorn/prefer-dom-node-append": e,
			"unicorn/prefer-dom-node-remove": e,
			"unicorn/prefer-dom-node-text-content": e,
			"unicorn/prefer-event-target": e,
			"unicorn/prefer-export-from": e,
			"unicorn/prefer-global-this": e,
			"unicorn/prefer-includes": e,
			"unicorn/prefer-keyboard-event-key": e,
			"unicorn/prefer-logical-operator-over-ternary": e,
			"unicorn/prefer-math-min-max": e,
			"unicorn/prefer-math-trunc": e,
			"unicorn/prefer-modern-dom-apis": e,
			"unicorn/prefer-modern-math-apis": e,
			"unicorn/prefer-module": e,
			"unicorn/prefer-native-coercion-functions": e,
			"unicorn/prefer-negative-index": e,
			"unicorn/prefer-node-protocol": e,
			"unicorn/prefer-number-properties": e,
			"unicorn/prefer-object-from-entries": e,
			"unicorn/prefer-optional-catch-binding": e,
			"unicorn/prefer-prototype-methods": e,
			"unicorn/prefer-query-selector": e,
			"unicorn/prefer-reflect-apply": e,
			"unicorn/prefer-regexp-test": e,
			"unicorn/prefer-set-has": e,
			"unicorn/prefer-set-size": e,
			"unicorn/prefer-spread": e,
			"unicorn/prefer-string-raw": e,
			"unicorn/prefer-string-replace-all": e,
			"unicorn/prefer-string-slice": e,
			"unicorn/prefer-string-starts-ends-with": e,
			"unicorn/prefer-string-trim-start-end": e,
			"unicorn/prefer-structured-clone": e,
			"unicorn/prefer-top-level-await": e,
			"unicorn/relative-url-style": e,
			"unicorn/require-array-join-separator": e,
			"unicorn/require-number-to-fixed-digits-argument": e,
			"unicorn/switch-case-braces": [e, "avoid"],
			"unicorn/text-encoding-identifier-case": e,
			"unicorn/throw-new-error": e,
		},
	},
	{
		name: "@vanyauhalin/wc-rules",
		files: ["**/*.cjs", "**/*.js", "**/*.jsx", "**/*.mjs", "**/*.cts", "**/*.mts", "**/*.ts", "**/*.tsx", "**/*.html"],
		rules: {
			"wc/attach-shadow-constructor": e,
			"wc/guard-define-call": e,
			"wc/guard-super-call": e,
			"wc/no-child-traversal-in-attributechangedcallback": e,
			"wc/no-child-traversal-in-connectedcallback": e,
			"wc/no-closed-shadow-root": e,
			"wc/no-constructor-attributes": e,
			"wc/no-constructor-params": e,
			"wc/no-customized-built-in-elements": e,
			"wc/no-invalid-element-name": e,
			"wc/no-invalid-extends": e,
			"wc/no-self-class": e,
			"wc/no-typos": e,
			"wc/require-listener-teardown": e,
			"wc/tag-name-matches-class": e,
		},
	},
	{
		name: "@vanyauhalin/yml-rules",
		files: ["**/*.yaml", "**/*.yml"],
		rules: {
			"yml/block-mapping-colon-indicator-newline": e,
			"yml/block-mapping-question-indicator-newline": e,
			"yml/block-mapping": e,
			"yml/block-sequence-hyphen-indicator-newline": e,
			"yml/block-sequence": e,
			"yml/flow-mapping-curly-newline": e,
			"yml/flow-mapping-curly-spacing": e,
			"yml/flow-sequence-bracket-newline": e,
			"yml/flow-sequence-bracket-spacing": e,
			"yml/indent": [e, 2, {indentBlockSequences: false, indicatorValueIndent: 2}],
			"yml/key-spacing": e,
			"yml/no-empty-document": e,
			"yml/no-empty-key": e,
			"yml/no-empty-sequence-entry": e,
			"yml/no-irregular-whitespace": e,
			"yml/no-multiple-empty-lines": e,
			"yml/no-tab-indent": e,
			"yml/no-trailing-zeros": e,
			"yml/plain-scalar": e,
			"yml/quotes": e,
			"yml/require-string-key": e,
			"yml/spaced-comment": e,
		},
	},

	// This integration should be after the main TypeScript definition.
	{
		name: "@vanyauhalin/markdown-rules/typescript-integration",
		files: ["**/*.md/*.cjs", "**/*.md/*.js", "**/*.md/*.jsx", "**/*.md/*.mjs", "**/*.md/*.cts", "**/*.md/*.mts", "**/*.md/*.ts", "**/*.md/*.tsx", "**/*.md/*.html"],
		rules: {
			"typescript/await-thenable": "off",
			"typescript/consistent-type-imports": "off",
			"typescript/dot-notation": "off",
			"typescript/naming-convention": "off",
			"typescript/no-array-delete": "off",
			"typescript/no-base-to-string": "off",
			"typescript/no-confusing-void-expression": "off",
			"typescript/no-deprecated": "off",
			"typescript/no-duplicate-type-constituents": "off",
			"typescript/no-floating-promises": "off",
			"typescript/no-for-in-array": "off",
			"typescript/no-implied-eval": "off",
			"typescript/no-meaningless-void-operator": "off",
			"typescript/no-misused-promises": "off",
			"typescript/no-mixed-enums": "off",
			"typescript/no-redundant-type-constituents": "off",
			"typescript/no-unnecessary-boolean-literal-compare": "off",
			"typescript/no-unnecessary-qualifier": "off",
			"typescript/no-unnecessary-template-expression": "off",
			"typescript/no-unnecessary-type-arguments": "off",
			"typescript/no-unnecessary-type-assertion": "off",
			"typescript/no-unsafe-enum-comparison": "off",
			"typescript/no-unsafe-unary-minus": "off",
			"typescript/non-nullable-type-assertion-style": "off",
			"typescript/only-throw-error": "off",
			"typescript/prefer-find": "off",
			"typescript/prefer-includes": "off",
			"typescript/prefer-nullish-coalescing": "off",
			"typescript/prefer-promise-reject-errors": "off",
			"typescript/prefer-reduce-type-parameter": "off",
			"typescript/prefer-regexp-exec": "off",
			"typescript/prefer-return-this-type": "off",
			"typescript/prefer-string-starts-ends-with": "off",
			"typescript/promise-function-async": "off",
			"typescript/related-getter-setter-pairs": "off",
			"typescript/require-array-sort-compare": "off",
			"typescript/require-await": "off",
			"typescript/restrict-plus-operands": "off",
			"typescript/restrict-template-expressions": "off",
			"typescript/return-await": "off",
			"typescript/switch-exhaustiveness-check": "off",
			"typescript/unbound-method": "off",
			"typescript/use-unknown-in-catch-callback-variable": "off",
		},
	},

	// This integration should be after the main unicorn definition.
	{
		name: "@vanyauhalin/markdown-rules/unicorn-integration",
		files: ["**/*.md/*"],
		rules: {
			"unicorn/filename-case": "off",
		},
	},

	//
	// Files
	//

	{
		name: "@vanyauhalin/c8-config-file",
		files: ["**/c8.config.json"],
		rules: {
			"jsonc/sort-array-values": [e, {pathPattern: "^reporter$", order: {type: "asc"}}],
			"jsonc/sort-keys": [e, {pathPattern: "^$", order: {type: "asc"}}],
		},
	},
	{
		name: "@vanyauhalin/eslint-config-file",
		files: ["**/eslint.config.cjs", "**/eslint.config.js", "**/eslint.config.mjs", "**/eslint.config.cts", "**/eslint.config.mts", "**/eslint.config.ts"],
		rules: {
			"import-x/no-default-export": "off",
		},
	},
	{
		name: "@vanyauhalin/tsconfig-file",
		files: ["**/jsconfig.json", "**/jsconfig.*.json", "**/tsconfig.json", "**/tsconfig.*.json"],
		rules: {
			"jsonc/no-comments": "off",
			"jsonc/sort-keys": [
				e,
				{
					pathPattern: "^$",
					order: ["extends", "compilerOptions", "references", "files", "include", "exclude"],
				},
				{
					pathPattern: "^compilerOptions$",
					order: {type: "asc"},
				},
			],
		},
	},
	{
		name: "@vanyauhalin/typedoc-file",
		files: ["**/typedoc.json"],
		rules: {
			"jsonc/no-comments": "off",
		},
	},
]

export default config
